# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('rrc-energy', ['core'])
    module.source = [
        'model/rrc-energy.cc',
        'helper/rrc-energy-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('rrc-energy')
    module_test.source = [
        'test/rrc-energy-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'rrc-energy'
    headers.source = [
        'model/rrc-energy.h',
        'helper/rrc-energy-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

