# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    bld.env['ENABLE_QD_CHANNEL'] = False

    obj = bld.create_ns3_program('mmwave-example', ['mmwave'])
    obj.source = 'mmwave-example.cc'
    obj = bld.create_ns3_program('mmwave-tcp-example', ['mmwave'])
    obj.source = 'mmwave-tcp-example.cc'
    obj = bld.create_ns3_program('mmwave-simple-epc', ['mmwave'])
    obj.source = 'mmwave-simple-epc.cc'
    obj = bld.create_ns3_program('mmwave-simple-epc-ipv6', ['mmwave'])
    obj.source = 'mmwave-simple-epc-ipv6.cc'
    obj = bld.create_ns3_program('mmwave-epc-tdma', ['mmwave'])
    obj.source = 'mmwave-epc-tdma.cc'   
    obj = bld.create_ns3_program('mmwave-tdma', ['mmwave'])
    obj.source = 'mmwave-tdma.cc'       
    obj = bld.create_ns3_program('mmwave-simple-building-obstacle', ['mmwave'])
    obj.source = 'mmwave-simple-building-obstacle.cc'
    obj = bld.create_ns3_program('mmwave-tcp-building-example', ['mmwave'])
    obj.source = 'mmwave-tcp-building-example.cc'
    obj = bld.create_ns3_program('mmwave-amc-test', ['mmwave'])
    obj.source = 'mmwave-amc-test.cc'
    obj = bld.create_ns3_program('mmwave-amc-test2', ['mmwave'])
    obj.source = 'mmwave-amc-test2.cc'
    obj = bld.create_ns3_program('mmwave-epc-amc-test', ['mmwave'])
    obj.source = 'mmwave-epc-amc-test.cc'    
    obj = bld.create_ns3_program('mc-twoenbs', ['mmwave'])
    obj.source = 'mc-twoenbs.cc' 
    obj = bld.create_ns3_program('mc-twoenbs-ipv6', ['mmwave'])
    obj.source = 'mc-twoenbs-ipv6.cc' 
    obj = bld.create_ns3_program('mmwave-ca-diff-bandwidth', ['mmwave'])
    obj.source = 'mmwave-ca-diff-bandwidth.cc' 
    obj = bld.create_ns3_program('mmwave-ca-same-bandwidth', ['mmwave'])
    obj.source = 'mmwave-ca-same-bandwidth.cc' 
    obj = bld.create_ns3_program('mmwave-beamforming-codebook-example', ['mmwave'])
    obj.source = 'mmwave-beamforming-codebook-example.cc' 

    if bld.env['ENABLE_QD_CHANNEL']:
        obj = bld.create_ns3_program('qd-channel-full-stack-example', ['mmwave','qd-channel'])
        obj.source = 'qd-channel-full-stack-example.cc'
