# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('mmwave-example', ['mmwave'])
    obj.source = 'mmwave-example.cc'
    obj = bld.create_ns3_program('mmwave-tcp-example', ['mmwave'])
    obj.source = 'mmwave-tcp-example.cc'
    obj = bld.create_ns3_program('mmwave-simple-epc', ['mmwave'])
    obj.source = 'mmwave-simple-epc.cc'

